services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    App\Service\Serializer\SerializerNormalizer:
      tags:
        - app.normalizer
    App\Migration\Migration:
      tags:
        - app.migration

  App\:
    resource: '../src'

  Symfony\Component\Console\Application:
    public: true

  Symfony\Component\BrowserKit\HttpBrowser:

  App\Service\Serializer:
    arguments:
      - !tagged_iterator app.normalizer

  App\Service\MigrationManager:
    arguments:
      - !tagged_iterator app.migration
